name: Label Pull Requests

on: pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  labeller:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          configuration-path: .github/labeller.yaml
          sync-labels: true
